### ISSUE TITLE
fixing sizing of co-op photos

### ISSUE THREAD

**Issue by katharineking** [umwics/wics-site#51]
sizes of co-op photos are not consistent. make all sizes the same.

<img width="334" alt="screen shot 2018-09-27 at 5 08 35 pm" src="https://user-images.githubusercontent.com/32337096/46177311-0aed7b80-c278-11e8-8670-16ccb3bb869f.png">

**Comment by jadasc** [comment]
@shenyunw I think this has been addressed?
