### ISSUE TITLE
Priceline Partner Network Co-op Modal

### ISSUE THREAD

**Issue by DiljotSG** [umwics/wics-site#59]
Add new modal for [Priceline Partner Network](https://pricelinepartnernetwork.com/) under the http://cs.umanitoba.ca/~wics/co-op/ page

Company link: https://pricelinepartnernetwork.com/

Company logo: 
![priceline-partner-network](https://user-images.githubusercontent.com/46803874/67647644-01ae6280-f901-11e9-997d-af6582016337.png)

**Comment by shenyunw** [comment]
![image](https://user-images.githubusercontent.com/20330938/67426690-3f795700-f5a0-11e9-8c30-cfa66044c5dc.png)

**Comment by robbenrose** [comment]
Added correct Priceline Partner Network logo to assets, changed company modal.
