### ISSUE TITLE
Ubisoft Modal

### ISSUE THREAD

**Issue by jadasc** [umwics/wics-site#78]
Add new modal for [Ubisoft Winnipeg](https://winnipeg.ubisoft.com/) under the http://cs.umanitoba.ca/~wics/co-op/ page

Company link: https://winnipeg.ubisoft.com/

**Comment by shenyunw** [comment]
![image](https://user-images.githubusercontent.com/20330938/67427124-1907eb80-f5a1-11e9-9b24-03c46af310be.png)
