### ISSUE TITLE
RBC Modal

### ISSUE THREAD

**Issue by jadasc** [umwics/wics-site#79]
Add new modal for [RBC](https://jobs.rbc.com/ca/en/students-graduates) under the http://cs.umanitoba.ca/~wics/co-op/ page

Company link: https://jobs.rbc.com/ca/en/students-graduates

**Comment by shenyunw** [comment]
![image](https://user-images.githubusercontent.com/20330938/67440805-ffc26780-f5bf-11e9-97cc-2975ff16c4bd.png)
