### ISSUE TITLE
PHAC Modal

### ISSUE THREAD

**Issue by jadasc** [umwics/wics-site#82]
Add new modal for [Public Health Agency of Canada](http://www.phac-aspc.gc.ca) under the http://cs.umanitoba.ca/~wics/co-op/ page

Company link: http://www.phac-aspc.gc.ca

**Comment by shenyunw** [comment]
![image](https://user-images.githubusercontent.com/20330938/67440782-ec170100-f5bf-11e9-95b0-dc156db9450d.png)
