### ISSUE TITLE
Blackberry Modal

### ISSUE THREAD

**Issue by jadasc** [umwics/wics-site#84]
Add new modal for [Blackberry](https://www.blackberry.com/ca/en) under the http://cs.umanitoba.ca/~wics/co-op/ page

Company link: https://www.blackberry.com/ca/en

**Comment by shenyunw** [comment]
![image](https://user-images.githubusercontent.com/20330938/67441055-f1288000-f5c0-11e9-91d4-eb904b8c69df.png)
